CREATE DATABASE portal_ipil;
USE portal_ipil;

CREATE TABLE usuarios (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
senha VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE noticias (
id INT AUTO_INCREMENT PRIMARY KEY,
titulo VARCHAR(255) NOT NULL,
resumo TEXT,
conteudo LONGTEXT,
imagem VARCHAR(255),
autor VARCHAR(100),
categoria VARCHAR(100),
data_publicacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
